import type { Metadata } from "next";
import { peydaFont } from "./_lib/fonts";
import { cn } from "@/lib/utils";
import "./globals.css";

export const metadata: Metadata = {
  title: "واکنشگر | یادگیری برنامه نویسی",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={cn(peydaFont.className, "dark", "antialiased")}>
        {children}
      </body>
    </html>
  );
}

//  <body className={`${peydaFont?.className} antialiased`}>{children}</body>
